"""empty message

Revision ID: 4567b3775346
Revises: 
Create Date: 2018-11-04 10:35:20.070076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4567b3775346'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
